language: go
sudo: required
addons:
  apt:
    packages:
    - lynx
    - jq
    - wget -q
    - grep
go:
- '1.10'
before_script:
- sudo rsync -az ${TRAVIS_BUILD_DIR}/ /usr/local/bootstrap/
- pushd packer
- if [ $VAGRANT_CLOUD_TOKEN ] ; then packer validate template.json ; fi
- popd
- bash scripts/install_consul.sh
- bash scripts/install_vault.sh
- bash scripts/install_redis.sh
- bash scripts/install_SecretID_Factory.sh
- sudo cp /home/travis/.vault-token /usr/local/bootstrap/.vault-token
script:
- source ./var.env
- export REDIS_MASTER_IP=127.0.0.1
- export LEADER_IP=127.0.0.1
- sudo VAULT_ADDR=http://127.0.0.1:8200 vault status
- consul kv put "development/REDIS_MASTER_IP" "127.0.0.1"
- consul kv put "development/LEADER_IP" "127.0.0.1"
- bash scripts/travis_run_go_app.sh
deploy:
  provider: releases
  api_key:
    secure: dAo/pXZ/jan3BcUA2bbhYl2v5QAW2JRAsaM0g077OJYxjUoepWarrb8puk0zdGfZ92ER+a7jwmXudbFVzk22Vp/aliIMkbrouQXVrXQaWZq0H45XD3grC5Pgbjdbn/s7gfCXk6IsZNkc1ztkpluFGox7iZXIYsrWJDvnjMNuhs6KWQpymKD8VQaQU1AqnWOOCWmkqLOy7pXtf9XQS44I5KkUibNFc5vxDqZriNCAkVSYZbvhmEphRb2iWGEtTxrJtU61Gj+fVpu6wpEO0JgWZNqmJTXgIXiPYb9i//uuRnA8qVym+PBl2azkMrmRV7TFbyzes1S5P5aWq0SgcYPKDtb7c5zJUzZkvpqkGDvriLUO2qyZq5PIC1Ega/bzLQMj/Nd8OMaJZjjoTNDc8frqQ9j84Q1WYTt1mhkMJF4LjXTar45nomR2GjBWfrETQBCGmO4fKYyNctx4cg8arz7MwftPIEt6orDegQzu8HR5oCX0hBvzDwK96JGtT8vfC4LfhtftTtTO2VqIMZ7lPbHzgyIswSBcVc9B7VIPS4Zka8JEzO1CRzeoL9u6HWNsUnre/U+twyxNmkZ1ZQW1kjeet8PT6S7eVRJuMofQJwhP42gz3yve8LaDaOxihlmD+UHnBVpDGSYl2ieLr+TAh2uwBNhs0bdEHJFNfwvNg9ySXKs=
  file_glob: true
  file: 
    - "./webcounter"
  skip_cleanup: true
  on:
    repo: allthingsclowd/web_page_counter
    tags: true
